package SheriffsssPackage;

import java.util.List;

import SheriffsssPackage.render.EquipmentHudView;
import SheriffsssPackage.render.ScoreHudView;
import SheriffsssPackage.render.TrainingHudView;

public interface GameView {
  AssetManager getAssets();
  AudioManager getAudio();
  GameInput getInput();
  DebugOptions getDebugOptions();
  State getState();
  GameMap getMap();
  Player getPlayer();
  int getCameraCenterWorldX();
  int getCameraCenterWorldY();
  double getCameraZoom();
  boolean isSpectating();
  List<Enemy> getEnemies();
  List<Projectile> getProjectiles();
  List<FlameBurstEffect> getFlameBurstEffects();
  List<CombatFloatingText> getCombatFloatingTexts();
  boolean isDeathOverlayActive();
  boolean isUsingTool();
  int getToolUseTicks();
  int getToolUseDurationTicks();
  MapObject getToolTargetObject();
  int getRevolverFlashTicks();
  int getRevolverFlashWorldX();
  int getRevolverFlashWorldY();
  int getRevolverFlashRadiusTiles();
  double getRevolverFlashIntensity();
  double getEquippedPlayerAccuracy();
  int heldItemOriginWorldX(Player sourcePlayer, ItemDefinition definition, Facing facing);
  int heldItemOriginWorldY(Player sourcePlayer, ItemDefinition definition, Facing facing);
  EquipmentHudView getEquipmentHudView();
  int getInfoMessageSlotCount();
  String getInfoMessage(int index);
  int getInfoMessageTicks(int index);
  String getSettingsMessage();
  boolean isPendingFullscreen();
  boolean isDebugMenuOpen();
  boolean isSettingsDebugButtonHovered();
  int getSettingsDebugButtonX();
  int getSettingsDebugButtonY();
  int getSettingsDebugButtonWidth();
  int getSettingsDebugButtonHeight();
  int getSettingsOverlayOffsetY();
  double getWindowResolutionSliderValue();
  String getWindowResolutionLabel();
  ScoreHudView getScoreHudView();
  List<int[]> getHealthPickups();
  int getDeathMenuButtonX();
  int getDeathMenuButtonY();
  int getDeathMenuButtonW();
  int getDeathMenuButtonH();
  long getFrameCount();
  DayNightCycle getDayNightCycle();
  TrainingHudView getTrainingHudView();
}
